"""add_candle_patterns_table

Revision ID: 37b5c23f3c31
Revises: 9a10028833e2
Create Date: 2026-06-04 03:52:57.959930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37b5c23f3c31'
down_revision = '9a10028833e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('candle_pattern_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_strategies_candle_pattern_id'), ['candle_pattern_id'], unique=False)
        batch_op.create_foreign_key(None, 'candle_patterns', ['candle_pattern_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_strategies_candle_pattern_id'))
        batch_op.drop_column('candle_pattern_id')

    # ### end Alembic commands ###
