"""add virtual_ts to execution_log for replay times

Revision ID: 7eb5d858a5a7
Revises: c9d0e1f2a3b4
Create Date: 2026-06-16 05:47:06.149973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7eb5d858a5a7'
down_revision = 'c9d0e1f2a3b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('execution_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('virtual_ts', sa.String(length=19), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('execution_logs', schema=None) as batch_op:
        batch_op.drop_column('virtual_ts')

    # ### end Alembic commands ###
