"""add_stop_loss_target_rules_to_strategies

Revision ID: 90f4f6458423
Revises: 37b5c23f3c31
Create Date: 2026-06-04 05:22:03.164391

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '90f4f6458423'
down_revision = '37b5c23f3c31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stop_loss_rules', mysql.JSON(), nullable=True))
        batch_op.add_column(sa.Column('target_rules', mysql.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.drop_column('target_rules')
        batch_op.drop_column('stop_loss_rules')

    # ### end Alembic commands ###
