"""nullable_session_id_manual_orders

Revision ID: 93c218990913
Revises: b808368ce221
Create Date: 2026-06-02 11:18:03.455932

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '93c218990913'
down_revision = 'b808368ce221'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('live_orders', schema=None) as batch_op:
        batch_op.alter_column('session_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('paper_orders', schema=None) as batch_op:
        batch_op.alter_column('session_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paper_orders', schema=None) as batch_op:
        batch_op.alter_column('session_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('live_orders', schema=None) as batch_op:
        batch_op.alter_column('session_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
