"""Initial migration: Create all models

Revision ID: b808368ce221
Revises: 
Create Date: 2026-06-02 04:59:34.008010

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b808368ce221'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'CUSTOMER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=True),
    sa.Column('payload', mysql.JSON(), nullable=True),
    sa.Column('response', mysql.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('kite_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('api_key_encrypted', sa.String(length=255), nullable=False),
    sa.Column('api_secret_encrypted', sa.String(length=255), nullable=False),
    sa.Column('access_token_encrypted', sa.String(length=255), nullable=True),
    sa.Column('token_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('static_ip', sa.String(length=45), nullable=True),
    sa.Column('is_connected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kite_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kite_configs_user_id'), ['user_id'], unique=True)

    op.create_table('paper_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('exchange', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('avg_buy_price', sa.Float(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('unrealised_pnl', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'symbol', name='uq_user_symbol_position')
    )
    with op.batch_alter_table('paper_positions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paper_positions_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_positions_user_id'), ['user_id'], unique=False)

    op.create_table('strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('instrument', sa.String(length=50), nullable=False),
    sa.Column('exchange', sa.Enum('NSE', 'BSE', name='exchange'), nullable=False),
    sa.Column('order_type', sa.Enum('MARKET', 'LIMIT', name='ordertype'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('entry_condition', mysql.JSON(), nullable=False),
    sa.Column('exit_condition', mysql.JSON(), nullable=False),
    sa.Column('stop_loss_pct', sa.Float(), nullable=False),
    sa.Column('take_profit_pct', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategies_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategies_name'), ['name'], unique=True)

    op.create_table('virtual_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('initial_balance', sa.Float(), nullable=False),
    sa.Column('total_realised_pnl', sa.Float(), nullable=False),
    sa.Column('reset_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('virtual_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_virtual_accounts_user_id'), ['user_id'], unique=True)

    op.create_table('trading_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.Enum('LIVE', 'PAPER', name='sessionmode'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'STOPPED', 'COMPLETED', name='sessionstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_stop_reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trading_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trading_sessions_strategy_id'), ['strategy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trading_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('user_strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'strategy_id', name='uq_user_strategy')
    )
    with op.batch_alter_table('user_strategies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_strategies_strategy_id'), ['strategy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_strategies_user_id'), ['user_id'], unique=False)

    op.create_table('live_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('kite_order_id', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('exchange', sa.String(length=10), nullable=False),
    sa.Column('transaction_type', sa.Enum('BUY', 'SELL', name='transactiontype'), nullable=False),
    sa.Column('order_type', sa.Enum('MARKET', 'LIMIT', name='ordertype'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'OPEN', 'PARTIALLY_FILLED', 'FILLED', 'CANCELLED', 'REJECTED', 'EXPIRED', name='orderstatus'), nullable=False),
    sa.Column('tag', sa.String(length=100), nullable=True),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['trading_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('live_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_live_orders_kite_order_id'), ['kite_order_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_live_orders_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_live_orders_user_id'), ['user_id'], unique=False)

    op.create_table('paper_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('exchange', sa.String(length=10), nullable=False),
    sa.Column('transaction_type', sa.Enum('BUY', 'SELL', name='paperordertype'), nullable=False),
    sa.Column('order_type', sa.Enum('MARKET', 'LIMIT', name='paperordercategory'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('trigger_price', sa.Float(), nullable=False),
    sa.Column('fill_price', sa.Float(), nullable=True),
    sa.Column('fill_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'FILLED', 'CANCELLED', name='paperorderstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['trading_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paper_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paper_orders_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_orders_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paper_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paper_orders_user_id'))
        batch_op.drop_index(batch_op.f('ix_paper_orders_session_id'))

    op.drop_table('paper_orders')
    with op.batch_alter_table('live_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_live_orders_user_id'))
        batch_op.drop_index(batch_op.f('ix_live_orders_session_id'))
        batch_op.drop_index(batch_op.f('ix_live_orders_kite_order_id'))

    op.drop_table('live_orders')
    with op.batch_alter_table('user_strategies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_strategies_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_strategies_strategy_id'))

    op.drop_table('user_strategies')
    with op.batch_alter_table('trading_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trading_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_trading_sessions_strategy_id'))

    op.drop_table('trading_sessions')
    with op.batch_alter_table('virtual_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_virtual_accounts_user_id'))

    op.drop_table('virtual_accounts')
    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategies_name'))
        batch_op.drop_index(batch_op.f('ix_strategies_created_by'))

    op.drop_table('strategies')
    with op.batch_alter_table('paper_positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paper_positions_user_id'))
        batch_op.drop_index(batch_op.f('ix_paper_positions_symbol'))

    op.drop_table('paper_positions')
    with op.batch_alter_table('kite_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kite_configs_user_id'))

    op.drop_table('kite_configs')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_event_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
