"""add_zone_configs_table

Revision ID: e79c72d32806
Revises: 3f7e8c9d4a2b
Create Date: 2026-06-08 01:47:18.154062

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e79c72d32806'
down_revision = '3f7e8c9d4a2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zone_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('fvg_settings', mysql.JSON(), nullable=True),
    sa.Column('sr_settings', mysql.JSON(), nullable=True),
    sa.Column('swing_settings', mysql.JSON(), nullable=True),
    sa.Column('confluence_settings', mysql.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('zone_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_zone_configs_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_zone_configs_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zone_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_zone_configs_name'))
        batch_op.drop_index(batch_op.f('ix_zone_configs_created_by'))

    op.drop_table('zone_configs')
    # ### end Alembic commands ###
